### ISSUE TITLE
Spike in current

### ISSUE THREAD

**Issue by mariwing** [turbokongen/hass-AMS#34]
Recently I have seen these kinds of spikes in current on my 3-phase meter. So far I have only seen it at l2. Is this something that could be handled in the code (disregard obviously corrupt data) or should I use a filter component in Home Assistant to get rid of them?

![image](https://user-images.githubusercontent.com/5949497/94468097-31768200-01c4-11eb-8d88-676c04dc4a0e.png)

**Comment by turbokongen** [comment]
The complete package is evaluated with two crc checksums before being decoded, so the corrupt data is coming from the meter itself.
Probably a firmware bug in the meter that have been introduced in a new firmware version, since this occured recently.
You should notify your grid supplier(nettleverandør) of this bug.
You can go back in your logs and see when this started, and supply that in the bugreport aswell.

**Comment by mariwing** [comment]
Thank you for the swift reply. I was not questioning your code 😊 I was thinking more like having a sanity check or filter. I agree that this should be fixed by the meter manufacturer. In the meantime I will use the range filter: https://www.home-assistant.io/integrations/filter/. I have some zwave plugs that also send spiked numbers so I already filter those.
